version: '3'
services:
  frontend:
    image: adrianofonseca/frontend-nginx:2.0
    ports:
     - "80:80"
    networks:
      - app
    depends_on:
      -  java-api
    deploy:
       replicas: 1
       update_config:
         parallelism: 1
         delay: 50s
       restart_policy:
         condition: on-failure 
       labels: [info=frontend]

  java-api:
    image: adrianofonseca/app:latest
    ports:
     - "8080"
     - "9990"
    networks:
      - app
    depends_on:
      - postgres
    deploy:
     replicas: 1
     update_config:
       parallelism: 1
       delay: 30s
     restart_policy:
       condition: on-failure 
     labels: [info=backend]


  postgres:
      image: adrianofonseca/postgres:9.5
      ports:
          - "5432"
      networks:
      - app
      environment:
          - DEBUG=false
          - DB_USER=app
          - DB_PASS=app
          - DB_NAME=app
      volumes:
          -  /home/adr-fonseca/docker/docker-postgres/postgresql/:/var/lib/postgresql
      deploy:
        labels: [info=database]
        placement:
          constraints: [node.role == manager]

networks:
      app:

